accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)
app_name = 'accounts'
from django.contrib.auth.views import login ,logout
urlpatterns = [

    url(r'^$', views.home),
#    url(r'^/login', login, {'template_name': 'accounts/login.html'}),
    url(r'^logout/', logout, {'template_name': 'accounts/logout.html'},name='logout'),

    url(r'^login',login, {'template_name': 'accounts/login.html'},name='login'),
     url(r'^register/', views.register,name='register'),
    url(r'^profile/$', views.profile, name='view_profile'),
url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

#    url(r'^reset-password/$', password_reset, name='reset_password'),
    #using our reset page view is password_rest by default just our form
    #url(r'^reset-password-mypage/', password_reset, {'template_name': 'accounts/password_reset.html'},name='reset_password1'),
    url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html'},name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done,name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete')

]

tutorial/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from tutorial import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls',namespace="accounts")),
    url(r'^$',views.login_redirect,name='login_redirect'),

]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.
class UserProfile(models.Model):

    user=models.OneToOneField(User)
    description=models.CharField(max_length=100 ,default='')
    city=models.CharField(max_length=100 ,default='')
    website=models.CharField(max_length=100 ,default='')
    phone=models.IntegerField(default=0)

def create_profile(sender, **kwargs):

    if kwargs ('created'):
        user_profile=UserProfile.objects.create(user=kwargs('instance'))

    post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from accounts.forms import (
    RegistrationForm,
    EditProfileForm
)

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
'''
def home(request):
    #return HttpResponse('Home page')
    return render(request,'accounts/login.html')
'''

def home(request):
    '''#RENDER IS Combines a given template with a
    given context dictionary and returns an HttpResponse object with that rendered text.

    '''
    return render(request,'accounts/home.html')
def logout(request):
    #return HttpResponse('Home page')
    return render(request,'accounts/logout.html')

def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(home)
            #or return redirect(reverse('accounts:home'))
    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)

#Below is decorator so that unwanted profile view for non logined user
#@login_required
def profile(request):

    args = {'user': request.user}
    return render(request,'accounts/profile.html', args)
def edit_profile(request):
    if request.method == 'POST':
        form = UserChangeForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = UserChangeForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()

            # ''' update_session_auth_hash is use to
            # update the session with the new password hash so that a
            # user changing their own password wont log themselves out.
            # '''
            update_session_auth_hash(request, form.user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('/accounts/profile')
            #return HttpResponseRedirect(reverse('profile'))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })

tutorial/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/accounts/login')

accounts/templates/accounts/change_password.html
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}

<h1>HOME</h1>
{% block head %}
<title>HOME</title>
{% endblock %}
</head>
{% block body %}

<body>



<!--THIS
<div class="container">
<h1>WELCOME</h1>
login
<button class="btn btn-danger" type="button" name="button"></button>

</div>
<h2>
    {{myName}}
</h2>
{%for number in numbers%}
<li>
    {{number}}

</li>
{%endfor%}
--><h1>HOME PAGE</h1>
HOME PAGE

HOMIEEEE
</body>
{% endblock %}

</html>

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <p>
        You can log in here!
    </p>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>


</div>

{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block head %}
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
        <br>
        <div class="container">
            <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">Social Network</a>
              </div>

                 <div id="navbar" class="navbar-collapse collapse">

                     <!-- THIS WILL LIMIT TYPE OF PROFILE VIEW -->
                     {% if user.is_authenticated %}

                     <ul class="nav navbar-nav">
                   <li><a href="/accounts/">Home</a></li>
                    <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>


                         <!--WE SHOULD avoid hardcode uRL LIKE THIS-->
                         <!--<li><a href="/accounts/profile">Profile</a></li>-->

                         <!--AVOID HARDCODING-->
                   <!--    -->

                         <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                         <li><a href="{% url 'accounts:change_password' %}">CHANGE PASSWORD</a></li>
                    </ul>
               <!--/.nav-collapse -->
                 {% else %}
                 <ul class="nav navbar-nav">
                    <li><a href="/accounts/login">Login</a></li>
                    </ul>
               </div><!--/.nav-collapse -->
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/accounts/register">Register</a></li>

                    </ul>

                {% endif %}
            </div><!--/.container-fluid -->
          </nav>
        </div>
        {% block body %}
            <h1>Base</h1>
        {% endblock %}
    </body>
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>